name: Deploy full-stack to EC2 instance

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Node.js on action runner instance
        uses: actions/setup-node@v4
        with:
          node-version: '26.5' # Specify your preferred Node version
          # cache: 'npm'         # Automatically caches npm dependencies
          
      - name: Setup Python on action runner instance
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Deploy to EC2 instance
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          ARGS: "-rlgoDzvc -i --delete"
          SOURCE: "./"
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USER }}
          TARGET: "/home/${{ secrets.EC2_USER }}/YABANKAPP"
          SCRIPT_BEFORE: |
            whoami
            ls -al
            sudo apt update && sudo apt upgrade -y
            sudo apt install nodejs npm -y
            node -v
            npm -v
            sudo apt install python3 -y
            sudo apt install python3-pip python3-venv -y
            sudo npm install -g pm2 -y
          SCRIPT_AFTER: |
            whoami
            ls -al
            
            cd "/home/${{ secrets.EC2_USER }}/YABANKAPP
            python3 -m venv .venv
            source .venv/bin/activate
            cd "/home/${{ secrets.EC2_USER }}/YABANKAPP/backend"
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            
            sudo cp yabankback.service /etc/systemd/system/yabankback.service
            sudo systemctl daemon-reload
            sudo systemctl enable yabankback.service
            sudo systemctl start yabankback.service
            sudo systemctl status yabankback.service

            pm2 start npm --name "/home/ubuntu/YABANKAPP/frontend" -- run dev
            pm2 startup
            pm2 save
            
            echo $RSYNC_STDOUT
      
